<?php 
define('SITE_NAM','齐享云-齐享网盘,免费网盘,文件分享'); 
define('SITE_KEY','网盘,免费网盘,齐享云'); 
define('SITE_DES','是国内一家数据存储服务的网站，历时多年，打造稳定高速网盘，为用户提供免费快捷的存储空间'); 
define('SAVE_DIR','system'); 
define('DEBUG','1'); 
define('FORSEARCH','1'); 
define('TASK_RUNTIME','1'); 
define('SITEMAP_RUNTIME','24'); 
define('FONTFILE',''); 
define('SHIELDWORD','A片,黄片'); 
define('PREFIX_AD','[齐享云]'); 
define('SITE_ICP',''); 
define('SITE_QQ',''); 
define('SITE_EMAIL',''); 
define('SITE_TEL',''); 
define('SITE_TONGJI',''); 
define('SITE_CLOSE','1'); 
define('SITE_CLOSE_REASON','站点维护中'); 
 ?>